"let mapleader = ","
:set incsearch
:set nu
":set expandtab
:set tabstop=3
:set shiftwidth=2
:set autoindent
:set smartindent
:syn on
:set noswapfile
:set hlsearch

:highlight HLONE ctermbg=green ctermfg=white
:highlight HLTWO ctermbg=blue ctermfg=white

nnoremap q :mat HLONE "<C-R><C-W>"<CR>
nnoremap Q :2mat HLTWO "<C-R><C-W>"<CR>
nnoremap qq :mat none<CR>
nnoremap QQ :2mat none<CR>

nnoremap <C-t>     :tabnew<CR>
inoremap <C-t>     <Esc>:tabnew<CR>
nnoremap <C-h> gT
nnoremap <C-l> gt

nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

"folding settings
"let php_folding=1
"set foldmethod=syntax   "fold based on indent
set foldnestmax=3      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use
set foldlevelstart=2

nnoremap zq zfa}
nnoremap <bar> :set invnumber<CR>

set nocompatible               " be iMproved
filetype off                   " required!

"set rtp+=~/.vim/bundle/vundle/
"call vundle#rc()

" let Vundle manage Vundle
" required! 
"Bundle 'gmarik/vundle'

" My Bundles here:

"Bundle 'Syntastic'
"Bundle 'maksimr/vim-jsbeautify'
"Bundle 'tomtom/tcomment_vim'
"Bundle 'nathanaelkane/vim-indent-guides'
"Bundle 'scrooloose/nerdtree'
" Bundle 'jistr/vim-nerdtree-tabs'
" Bundle 'Yggdroot/indentLine'

filetype plugin indent on     " required!

"autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
" for html
"autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
" for css or scss
"autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>

:set encoding=utf-8
:set t_Co=256

"let g:indent_guides_auto_colors = 0
"let g:indent_guides_enable_on_vim_startup=1
"autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=0
"autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=8
"let g:indent_guides_start_level=1
"let g:indent_guides_guide_size=1

"let g:nerdtree_tabs_open_on_console_startup=1
"map <C-n> :NERDTreeTabsToggle<CR>
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

:set tabstop=3
