# remap prefix from 'C-b' to `
set -g default-shell /usr/bin/zsh

set -g default-terminal "screen-256color"
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

# if run as "tmux attach", create a session if one does not already exist
new-session -n $HOST

set -gq utf8 on

set -g mouse on
#set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'

set -g terminal-overrides ',*:indn@'

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind Left if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind Down if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind Up if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind Right if-shell "$is_vim" "send-keys C-l" "select-pane -R"
#bind \ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# split panes using | and = and send to vim if its vim
bind - if-shell "$is_vim" "send-keys C-w s"  "split-window -v"
bind = if-shell "$is_vim" "send-keys C-w v"  "split-window -h"
bind _ "split-window -v"
bind + "split-window -h"
unbind '"'
unbind %


set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Status update interval
set -g status-interval 15

# Basic status bar colors

set -g status-left-length 15
set -g status-left "[#S]"

# Right side of status bar
set -g status-right-length 65
set -g status-right "#(who | cut -d \" \" -f1)@#h | %H:%M %b %d, %Y"

# Window status
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# Window separator
set -g window-status-separator " "

# Window status alignment
set -g status-justify left

# Pane number indicator

# Clock mode
set -g clock-mode-style 24

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

