:set incsearch
:set nu
:set expandtab
:set tabstop=2
:set shiftwidth=2
:set sts=2
:set autoindent
:set smartindent
:syn on
:set noswapfile
:set hlsearch
set mouse=a
set wrap
set linebreak

set list
set listchars+=tab:┊\ 
set listchars+=eol:\ 
"set listchars+=space:·

"set cursorcolumn
"set cursorline

nnoremap <C-t>     :tabnew<CR>
inoremap <C-t>     <Esc>:tabnew<CR>

" nmap <silent> <A-Up> :wincmd k<CR>
" nmap <silent> <A-Down> :wincmd j<CR>
" nmap <silent> <A-Left> :wincmd h<CR>
" nmap <silent> <A-Right> :wincmd l<CR>

set splitbelow
set splitright


"folding settings
"let php_folding=1
"set foldmethod=syntax   "fold based on indent
set foldnestmax=3      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use
"set foldlevelstart=2

set nocompatible               " be iMproved
"filetype off                   " required!

" set rtp+=~/.vim/bundle/vundle
" call vundle#rc()

" let Vundle manage Vundle
" required! 
" Bundle 'gmarik/vundle'

" My Bundles here:

function! BuildYCM(info)
  if a:info.status == 'installed' || a:info.force
    !./install.sh --clang-completer --ts-completer
  endif
endfunction

call plug#begin('~/.vim/plugged')

Plug 'tomtom/tcomment_vim'
Plug 'scrooloose/nerdtree'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-syntastic/syntastic'
" Plug 'w0rp/ale'
" Plug 'zefei/vim-wintabs'
Plug 'editorconfig/editorconfig-vim'
Plug 'chrisbra/vim-diff-enhanced'
Plug 'altercation/vim-colors-solarized'
Plug 'Valloric/YouCompleteMe', { 'do': function('BuildYCM') }
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" Plug 'pangloss/vim-javascript'
Plug 'othree/yajs.vim'
Plug 'mxw/vim-jsx'
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }
" Plug 'flazz/vim-colorschemes'
Plug 'felixhummel/setcolors.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'ryanoasis/vim-devicons'
Plug 'chrisbra/csv.vim'
" Plug 'google/vim-colorscheme-primary'
" Plug 'Quramy/vim-js-pretty-template'
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'branch': 'release/0.x'
  \ }

call plug#end()

syntax enable
" set background=dark
" colorscheme solarized
" colorscheme primary
" colorscheme desert
colorscheme default

" let g:solarized_diffmode="high"

if &diff
	colorscheme desert
endif

set completeopt-=preview

set diffopt+=iwhite
set diffexpr=DiffW()
function DiffW()
  let opt = ""
   if &diffopt =~ "icase"
     let opt = opt . "-i "
   endif
   if &diffopt =~ "iwhite"
     let opt = opt . "-w " " swapped vim's -b with -w
   endif
   silent execute "!diff -a --binary " . opt .
     \ v:fname_in . " " . v:fname_new .  " > " . v:fname_out
endfunction

"filetype plugin indent on     " required!

:set encoding=utf-8

:set tenc=utf8

:set isprint=

if !has('gui_running')
  set t_Co=256
endif

" if (has("termguicolors"))
"   set termguicolors
" endif

"let g:nerdtree_tabs_open_on_console_startup=1
map <C-n> :NERDTreeToggle<CR>
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

highlight HLONE cterm=NONE ctermbg=green ctermfg=white
highlight HLTWO cterm=NONE ctermbg=red ctermfg=white

nnoremap q :mat HLONE "<C-R><C-W>"<CR>
nnoremap Q :2mat HLTWO "<C-R><C-W>"<CR>
nnoremap qq :mat none<CR>
nnoremap QQ :2mat none<CR>



" nmap <silent> <C-u> :split<CR>
" nmap <silent> <C-i> :vsplit<CR>
nmap <silent> <C-o> :CtrlPBuffer<CR>

let g:ctrlp_cmd='CtrlP :pwd'

" nmap <silent> <C-p> :CtrlP<CR>
let g:ctrlp_working_path_mode = 'ra'

" menu completion in command mode on <tab>
set wildmenu
" <tab> cycles between all matching choices.
set wildmode=full
" ignore these files when completing
set wildignore+=*.o,*.obj,.git,*.pyc


"set wildchar=<Tab> wildmenu wildmode=full
set wildcharm=<C-Z>
nnoremap <F10> :b <C-Z>

" Mappings to access buffers (don't use "\p" because a
" delay before pressing "p" would accidentally paste).
" \l       : list buffers
" \b \f \g : go back/forward/last-used
" \1 \2 \3 : go to buffer 1/2/3 etc
nnoremap <Leader>l :ls<CR>
nnoremap <Leader>b :bp<CR>
nnoremap <Leader>f :bn<CR>
nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>

let g:ctrlp_custom_ignore = 'node_modules\|build\|DS_Store\|coverage\|build'
" let g:ctrlp_custom_ignore = '\v[\/]\.(DS_Store|git|hg|svn|optimized|compiled|build|node_modules)$'


:set tabstop=3

"set noshowmode

"write everything
set autowriteall

" use <ctrl> hjkl to move between buffers
map <c-j> :bp <CR>
map <c-k> :bn <CR>
map <c-h> :bfirst <CR>
map <c-l> :blast <CR>

highlight DiffAdd    cterm=NONE ctermfg=0 ctermbg=2
highlight DiffDelete cterm=NONE ctermfg=0 ctermbg=1
highlight DiffChange cterm=NONE ctermfg=0 ctermbg=2
highlight DiffText   cterm=NONE ctermfg=0 ctermbg=6

autocmd FilterWritePre * if &diff | setlocal wrap< | endif

set rulerformat=%30(%f%=%l,%c%V\ %P%)

function! s:DiffWithSaved()
  let filetype=&ft
  diffthis
  vnew | r # | normal! 1Gdd
  diffthis
  exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
com! DiffSaved call s:DiffWithSaved()

function! C2cjs()
  " Save cursor position
  let l:save = winsaveview()
  " Remove trailing whitespace
  %s/import\s\+\(.\+\)\s\+from\s\+\('.\+'\);/const \1 = require(\2);/g
  " Move cursor to original position
  call winrestview(l:save)
endfunction

" noremap <Up> <NOP>
" noremap <Down> <NOP>
" noremap <Left> <NOP>
" noremap <Right> <NOP>
inoremap <C-x> <esc>:qa<cr>               " quit discarding changes
nnoremap <C-x> :qa<cr>

inoremap <C-b> <esc>:bd<cr>               " quit discarding changes
nnoremap <C-b> :bd<cr>

inoremap <F2> <esc>:w<cr>:bd<cr>
nnoremap <F2> <esc>:w<cr>:bd<cr>

if &diff
    set cursorline
    map ] ]c
    map [ [c
endif

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = 'yarn eslint --'
let g:jsx_ext_required = 0


let g:airline_section_x=''
let g:airline_section_y=''
let g:airline_theme='bubblegum'

autocmd Filetype gitcommit setlocal spell textwidth=72

" noremap  <Up> ""
" noremap! <Up> <Esc>
" noremap  <Down> ""
" noremap! <Down> <Esc>
" noremap  <Left> ""
" noremap! <Left> <Esc>
" noremap  <Right> ""
" noremap! <Right> <Esc>


" if hidden is not set, TextEdit might fail.
set hidden

" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup

" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
set signcolumn=yes

:set cmdheight=1

set autowriteall
