#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
$DIR/profiles/ubuntu

sudo add-apt-repository universe
sudo add-apt-repository multiverse
sudo apt update
sudo apt install -y ubuntu-restricted-extras

sudo apt-get remove -y --purge gnome-sudoku gnome-calendar gnome-todo gnome-mines gnome-mahjongg aisleriot shotwell totem totem-plugins gedit

sudo apt-get install -y thunderbird gparted calibre torbrowser-launcher geany ttf-mscorefonts-installer meld zeal gnome-tweaks dconf-editor chromium-browser vlc gimp 

sudo add-apt-repository ppa:appimagelauncher-team/stable
sudo apt update
sudo apt install -y appimagelauncher

# sudo apt-get install -y kazam adb wmctrl xdotool

# FILESDIRECTORY='/home/files'
# if [ -d "$FILESDIRECTORY" ]; then
#   mkdir -p ${FILESDIRECTORY}/bin
#   mkdir -p ${FILESDIRECTORY}/Applications
#   cd ~
#   ln -s ../files/bin
#   ln -s ../files/Applications
# else
#   mkdir -p ~/bin
#   mkdir -p ~/Applications
# fi

echo 'enabled=False' > ~/.config/user-dirs.conf

$DIR/profiles/snapui

sudo npm i -g lighthouse

# wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /tmp/googlechrome.deb
# sudo gdebi -n /tmp/googlechrome.deb

#Fonts
mkdir -p ~/.local/share/fonts
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraMono.zip -O /tmp/nerdfonts.zip
unzip /tmp/nerdfonts.zip -d ~/.local/share/fonts/
fc-cache -f

#geany colorschemes
wget https://raw.github.com/geany/geany-themes/master/colorschemes/solarized-dark.conf -O ~/.config/geany/colorschemes/solarized-dark.conf

#vscode fixes
sudo sh -c 'echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf'
sudo sysctl -p

wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code

echo "
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/lastSuccessfulBuild/artifact/build/

setup firefox

https://www.mongodb.com/download-center/compass?jmp=docs

setup gnome online accounts

setup vscode

reboot

" > ~/Documents/notes/todo.txt

sudo apt autoremove
