#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

##Add self to suoders
ME=$(whoami)
sudo sh -c "echo '$ME ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/$ME"

#curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -


sudo apt update
sudo apt -y upgrade

sudo apt install -y vim gdebi tmux zsh fonts-powerline ruby wget p7zip unrar-free tree htop git curl editorconfig unzip git-extras nnn software-properties-common apt-transport-https
sudo apt install -y mongo-tools mongodb-clients 
sudo apt install -y openssh-server 
sudo apt install -y httpie fortune-mod cowsay lolcat
#sudo snap install node --channel=12/stable --classic
sudo apt install -y nodejs 
sudo apt install -y python3-pip 
sudo apt install -y flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

sudo npm i -g speed-test yarn npm-check-updates

# sudo apt install -y flatpak
# flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo


$DIR/profiles/zsh
$DIR/profiles/vim
$DIR/profiles/tmux
$DIR/profiles/git
$DIR/profiles/pip
# $DIR/profiles/snap

