#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

rm -f ~/.vimrc
ln -s $DIR/conf/vimrc ~/.vimrc

if [ -f ~/.vim/autoload/plug.vim ]; then
  #do nothing
  :
else 
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -c 'PlugInstall' -c 'qa!'
