#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

if [ -d ~/.oh-my-zsh ]; then
  #do nothing
  :
else 
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi
if [ -d ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search ]; then
  #do nothing
  :
else 
  git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search
fi

echo "source $DIR/conf/zsh/zshrc" > ~/.zshrc
echo "source $DIR/conf/zsh/functions" >> ~/.zshrc
echo "source $DIR/conf/zsh/aliases" >> ~/.zshrc

rm -f ~/.p10k.zsh
ln -s $DIR/conf/zsh/p10k.zsh ~/.p10k.zsh

chsh
