#!/bin/bash

##Add self to suoders
ME=$(whoami)
sudo sh -c "echo '$ME ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/$ME"

sudo add-apt-repository -y ppa:jonathonf/vim
sudo add-apt-repository -y ppa:twodopeshaggy/jarun

##update and upgrade
sudo apt-get update
#sudo apt-get upgrade -y

sudo apt-get install -y python-pip

##install ubuntu universe packages
sudo apt-get install -y curl gdebi wget p7zip unrar-free tree htop fortune cowsay cmatrix
sudo apt-get install -y vim git tmux editorconfig dos2unix trash-cli xsel unzip git-extras nnn
sudo apt-get install -y speedtest-cli 
sudo apt-get install -y googler
sudo add-apt-repository ppa:ultradvorka/ppa && sudo apt-get update && sudo apt-get install hh && hh --show-configuration >> ~/.bashrc

sudo pip install --upgrade pip
sudo pip install glances
# sudo apt-get install -y ytalk 

