#!/bin/bash

##Add self to suoders
ME=$(whoami)
sudo sh -c "echo '$ME ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/$ME"

sudo add-apt-repository -y ppa:jonathonf/vim
sudo add-apt-repository -y ppa:twodopeshaggy/jarun
sudo add-apt-repository -y ppa:ultradvorka/ppa
sudo add-apt-repository -y ppa:aacebedo/fasd

##update and upgrade
sudo apt-get update
#sudo apt-get upgrade -y

sudo apt-get install -y python-pip

##install ubuntu universe packages
sudo apt-get install -y curl gdebi wget p7zip unrar-free tree htop fortune cowsay cmatrix
sudo apt-get install -y vim git tmux editorconfig dos2unix trash-cli xsel unzip git-extras nnn
sudo apt-get install -y speedtest-cli 
sudo apt-get install -y googler httpie
sudo apt-get install -y hh && hh --show-configuration >> ~/.bashrc
sudo apt-get install -y fasd


sudo pip install --upgrade pip
sudo pip install glances
sudo pip install howdoi

# sudo apt-get install -y ytalk 

